name: Sync Leetcode

on:
  workflow_dispatch: # 내가 버튼 누를 때 실행
  schedule:
    - cron: "0 8 * * 6" # 매주 토요일 오전 8시에 자동 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions # 저장될 폴더 이름
